---
- hosts: all
  
  tasks:
    - name: Disable password login
      lineinfile: 
        dest: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
      become: true
           
    - name: Restart SSH Daemon
      service:
        name: sshd
        state: restarted
      become: true