---
- hosts: all
    - name: Disable password login
      lineinfile: dest={{ sshd_config }} regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"
      when: add_identity_key|success and not add_identity_key|skipped
      notify: restart sshd