---
- hosts: all
  
  tasks:
      - lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        
      - service:
        name: sshd
        state: restarted